### ISSUE TITLE
Pre-hackweek training

### ISSUE THREAD

**Issue by aaarendt** [ICESAT-2HackWeek/admin-issues#20]
```[tasklist]
### Tasks

- [ ] Consult with organizers to assess whether this training will be offered
- [ ] Assemble trainers / partner with Software Carpentry  
- [ ] Announce training, invite participants and create schedule
``` 

<details><summary>Details</summary>
<p>

Providing training resources to participants wishing to learn / get a refresher on fundamental data science tools such as GitHub and Jupyter.

</p>
</details>
